package com.vesalaakso.rbb.controller;

import java.util.List;

import org.newdawn.slick.Input;
import org.newdawn.slick.KeyListener;
import org.newdawn.slick.MouseListener;

import com.google.common.collect.Lists;

/**
 * Handles the coordination of different input based controllers.
 * 
 * @author Vesa Laakso
 */
public class InputMaster implements Updateable {

	/** The input that generates events */
	private Input input;

	/** List of controllers which would like to act upon every frame. */
	private List<Updateable> updateables = Lists.newLinkedList();

	/** Added mouse listeners. */
	private List<MouseListener> mouseListeners = Lists.newLinkedList();

	/** Added key listeners. */
	private List<KeyListener> keyListeners = Lists.newLinkedList();

	/** Is the input master paused or not */
	private boolean paused;

	/**
	 * Constructs an InputMaster and associates it with the given
	 * <code>Input</code>.
	 * 
	 * @param input
	 *            The <code>Input</code> that will generate events to listen to.
	 */
	public InputMaster(Input input) {
		this.input = input;
	}

	/**
	 * Makes the input generate events for the given <code>KeyListener</code>.
	 * 
	 * @param controller
	 *            the controller implementing <code>KeyListener</code> interface
	 *            and acting upon events generated by key pressed.
	 */
	public void addKeyListener(KeyListener controller) {
		input.addKeyListener(controller);
		keyListeners.add(controller);
		if (controller instanceof Updateable) {
			updateables.add((Updateable) controller);
		}
	}

	/**
	 * Makes the input generate events for the given <code>MouseListener</code>.
	 * 
	 * @param controller
	 *            the controller implementing <code>MouseListener</code>
	 *            interface and acting upon events generated by mouse.
	 */
	public void addMouseListener(MouseListener controller) {
		input.addMouseListener(controller);
		mouseListeners.add(controller);
		if (controller instanceof Updateable) {
			updateables.add((Updateable) controller);
		}
	}

	/** Pauses the added inputs from firing */
	public void pause() {
		if (paused) {
			return;
		}
		paused = true;
		for (MouseListener listener : mouseListeners) {
			input.removeMouseListener(listener);
		}
		for (KeyListener listener : keyListeners) {
			input.removeKeyListener(listener);
		}
	}

	/** Resumes the added inputs to fire again */
	public void unpause() {
		if (!paused) {
			return;
		}
		paused = false;
		for (MouseListener listener : mouseListeners) {
			input.addMouseListener(listener);
		}
		for (KeyListener listener : keyListeners) {
			input.addKeyListener(listener);
		}
	}

	/**
	 * Calls the update()-method on all attached <code>Controller</code>s.
	 * 
	 * @param delta
	 *            The amount of time thats passed since last update in
	 *            milliseconds
	 * 
	 * @see Controller#update(int)
	 */
	@Override
	public void update(int delta) {
		for (Updateable c : updateables) {
			c.update(delta);
		}
	}

}
